apiVersion: v1
kind: Service
metadata:
  name: {{ include "tensorflow-webshell.fullname" . }}
  labels:
    app_label: {{.Release.Name }}
    app.kubernetes.io/name: {{ include "tensorflow-webshell.name" . }}
    helm.sh/chart: {{ include "tensorflow-webshell.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.clusterservice | indent 4 }}
  selector:
    app.kubernetes.io/name: {{ include "tensorflow-webshell.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
