apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: data
    type: local
  name:  data
  namespace: default
spec:
  storageClassName: manual2
  accessModes:
  - ReadWriteOnce
  resources:
   requests:
    storage: 200Mi
