kind: Deployment
apiVersion: apps/v1beta1
metadata:
 name: nginx-init
spec:
  replicas: 1
  template:
   metadata:
    labels:
     app: nginx
   spec:
    containers:
    - name: webserver
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
    initContainers:
    - name: checkbackend
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["sh","-c","until nslookup backend.default.svc;do echo 'waiting backend to waiting for backend to come up'; sleep 3; done ; echo 'backend is up,ready to lauch web server'"]
