apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mypvc
  name:  mypvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
