apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ include "mxnet-webshell.fullname" . }}
  labels:
    app_label: {{.Release.Name }}
    app.kubernetes.io/name: {{ include "mxnet-webshell.name" . }}
    helm.sh/chart: {{ include "mxnet-webshell.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app_label: {{.Release.Name }}
        app.kubernetes.io/name: {{ include "mxnet-webshell.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mxnet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - "/bin/bash"
          args:
          - "-c"
          - "jupyter_start.sh 123456 && jupyter notebook / --ip 0.0.0.0 --allow-root"
          ports:
          - containerPort: 8888
          - containerPort: 6006
          - containerPort: 8500
          - containerPort: 9999
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: ceph
            mountPath: /mnt/ceph
      volumes:
{{ toYaml .Values.volumes | indent 6 }}
