apiVersion: v1
kind: Service
metadata:
  name: {{ include "pytorch-webshell.fullname" . }}
  labels:
    app_label: {{.Release.Name }}
    app.kubernetes.io/name: {{ include "pytorch-webshell.name" . }}
    helm.sh/chart: {{ include "pytorch-webshell.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
  selector:
    app.kubernetes.io/name: {{ include "pytorch-webshell.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
